### ISSUE TITLE
hey friend, are you planing to do a vue or react one?

### ISSUE THREAD

**Issue by Davidzhu001** [cssninjaStudio/friendkit#1]
Hey friend, i just bought the template. do you have any plan for a react or vue one?

**Comment by cssninjaStudio** [comment]
Hey,

Thanks for your purchase! About React, Iam not sure when or if we will do it. However, we are steadily converting our templates to make Vue 3 versions with Vite JS as bundler. We started with Huro, which is huge. We'll be continuing with others like Friendkit just afterwards. Regards.

**Comment by Davidzhu001** [comment]
@cssninjaStudio I just bought one horu. it is really awesome works you guys have done
